[package]
name = "meilisearch-types"
version = "0.8.4"
license = "MIT"
authors = ["Clément Renault <renault.cle@gmail.com>"]
edition = "2018"

[dependencies.zerocopy]
version = "0.2.8"
optional = true

[dependencies.serde]
version = "1.0.101"
features = ["derive"]
optional = true

[features]
default = ["serde", "zerocopy"]
